package com.boilerplate.server.dao;

import com.boilerplate.server.model.AreaStreet;
import com.boilerplate.server.model.AreaStreetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaStreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int countByExample(AreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int deleteByExample(AreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int insert(AreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int insertSelective(AreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    List<AreaStreet> selectByExample(AreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    AreaStreet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AreaStreet record, @Param("example") AreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AreaStreet record, @Param("example") AreaStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AreaStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AreaStreet record);
}