package com.boilerplate.server.model;

import java.io.Serializable;

public class AreaStreet implements Serializable {
    /**
     * 
     * 表字段 : area_street.id
     * @mbggenerated
     */
    private Integer id;

    /**
     * 区域编码
     * 表字段 : area_street.code
     * @mbggenerated
     */
    private String code;

    /**
     * 名称
     * 表字段 : area_street.name
     * @mbggenerated
     */
    private String name;

    /**
     * 是否街道标记
     * 表字段 : area_street.is_street
     * @mbggenerated
     */
    private Byte isStreet;

    /**
     * 父级编码
     * 表字段 : area_street.parent_code
     * @mbggenerated
     */
    private String parentCode;

    /**
     * 状态
     * 表字段 : area_street.status
     * @mbggenerated
     */
    private Byte status;

    /**
     * 创建时间
     * 表字段 : area_street.created_at
     * @mbggenerated
     */
    private Integer createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_street
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.id
     *
     * @return the value of area_street.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.id
     *
     * @param id the value for area_street.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.code
     *
     * @return the value of area_street.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.code
     *
     * @param code the value for area_street.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.name
     *
     * @return the value of area_street.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.name
     *
     * @param name the value for area_street.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.is_street
     *
     * @return the value of area_street.is_street
     *
     * @mbggenerated
     */
    public Byte getIsStreet() {
        return isStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.is_street
     *
     * @param isStreet the value for area_street.is_street
     *
     * @mbggenerated
     */
    public void setIsStreet(Byte isStreet) {
        this.isStreet = isStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.parent_code
     *
     * @return the value of area_street.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.parent_code
     *
     * @param parentCode the value for area_street.parent_code
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.status
     *
     * @return the value of area_street.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.status
     *
     * @param status the value for area_street.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_street.created_at
     *
     * @return the value of area_street.created_at
     *
     * @mbggenerated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_street.created_at
     *
     * @param createdAt the value for area_street.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_street
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", isStreet=").append(isStreet);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}