package com.boilerplate.server.model;

import java.io.Serializable;

public class Area implements Serializable {
    /**
     * 自增ID
     * 表字段 : area.id
     * @mbggenerated
     */
    private Integer id;

    /**
     * 名称
     * 表字段 : area.name
     * @mbggenerated
     */
    private String name;

    /**
     * 父级ID
     * 表字段 : area.parent_id
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * 地区层级
     * 表字段 : area.depth
     * @mbggenerated
     */
    private Byte depth;

    /**
     * 状态
     * 表字段 : area.status
     * @mbggenerated
     */
    private Boolean status;

    /**
     * 行政编码
     * 表字段 : area.admin_code
     * @mbggenerated
     */
    private String adminCode;

    /**
     * 天猫状态(是否在天猫服务区域内,1-在,0-不在)
     * 表字段 : area.tmall_status
     * @mbggenerated
     */
    private Short tmallStatus;

    /**
     * 创建时间
     * 表字段 : area.created_at
     * @mbggenerated
     */
    private Integer createdAt;

    /**
     * 类型
     * 表字段 : area.type
     * @mbggenerated
     */
    private Integer type;

    /**
     * 合伙人id
     * 表字段 : area.partner_id
     * @mbggenerated
     */
    private String partnerId;

    /**
     * 
     * 表字段 : area.initials
     * @mbggenerated
     */
    private String initials;

    /**
     * 区域id，对应region的主键ID
     * 表字段 : area.region_id
     * @mbggenerated
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.name
     *
     * @return the value of area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.name
     *
     * @param name the value for area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.parent_id
     *
     * @return the value of area.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.parent_id
     *
     * @param parentId the value for area.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.depth
     *
     * @return the value of area.depth
     *
     * @mbggenerated
     */
    public Byte getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.depth
     *
     * @param depth the value for area.depth
     *
     * @mbggenerated
     */
    public void setDepth(Byte depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.status
     *
     * @return the value of area.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.status
     *
     * @param status the value for area.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.admin_code
     *
     * @return the value of area.admin_code
     *
     * @mbggenerated
     */
    public String getAdminCode() {
        return adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.admin_code
     *
     * @param adminCode the value for area.admin_code
     *
     * @mbggenerated
     */
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode == null ? null : adminCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.tmall_status
     *
     * @return the value of area.tmall_status
     *
     * @mbggenerated
     */
    public Short getTmallStatus() {
        return tmallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.tmall_status
     *
     * @param tmallStatus the value for area.tmall_status
     *
     * @mbggenerated
     */
    public void setTmallStatus(Short tmallStatus) {
        this.tmallStatus = tmallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.created_at
     *
     * @return the value of area.created_at
     *
     * @mbggenerated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.created_at
     *
     * @param createdAt the value for area.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.type
     *
     * @return the value of area.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.type
     *
     * @param type the value for area.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.partner_id
     *
     * @return the value of area.partner_id
     *
     * @mbggenerated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.partner_id
     *
     * @param partnerId the value for area.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.initials
     *
     * @return the value of area.initials
     *
     * @mbggenerated
     */
    public String getInitials() {
        return initials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.initials
     *
     * @param initials the value for area.initials
     *
     * @mbggenerated
     */
    public void setInitials(String initials) {
        this.initials = initials == null ? null : initials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.region_id
     *
     * @return the value of area.region_id
     *
     * @mbggenerated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.region_id
     *
     * @param regionId the value for area.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", depth=").append(depth);
        sb.append(", status=").append(status);
        sb.append(", adminCode=").append(adminCode);
        sb.append(", tmallStatus=").append(tmallStatus);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", type=").append(type);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", initials=").append(initials);
        sb.append(", regionId=").append(regionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}