package com.boilerplate.server.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

public class UserOrder implements Serializable {
    /**
     * 订单号
     * 表字段 : user_order.order_id
     * @mbggenerated
     */
    private Long orderId;

    /**
     * 商家ID
     * 表字段 : user_order.shop_id
     * @mbggenerated
     */
    private Long shopId;

    /**
     * 用户ID
     * 表字段 : user_order.customer_id
     * @mbggenerated
     */
    private Long customerId;

    /**
     * 客户名称
     * 表字段 : user_order.customer_name
     * @mbggenerated
     */
    private String customerName;

    /**
     * 客户手机
     * 表字段 : user_order.customer_mobile
     * @mbggenerated
     */
    private String customerMobile;

    /**
     * 客户所在市
     * 表字段 : user_order.customer_city
     * @mbggenerated
     */
    private Integer customerCity;

    /**
     * 客户地址
     * 表字段 : user_order.customer_address
     * @mbggenerated
     */
    private String customerAddress;

    /**
     * 订单价格
     * 表字段 : user_order.order_price
     * @mbggenerated
     */
    private BigDecimal orderPrice;

    /**
     * 支付状态
     * 表字段 : user_order.pay_status
     * @mbggenerated
     */
    private Short payStatus;

    /**
     * 创建时间
     * 表字段 : user_order.create_time
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp createTime;

    /**
     * 更新时间
     * 表字段 : user_order.update_time
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_id
     *
     * @return the value of user_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_id
     *
     * @param orderId the value for user_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.shop_id
     *
     * @return the value of user_order.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.shop_id
     *
     * @param shopId the value for user_order.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.customer_id
     *
     * @return the value of user_order.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.customer_id
     *
     * @param customerId the value for user_order.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.customer_name
     *
     * @return the value of user_order.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.customer_name
     *
     * @param customerName the value for user_order.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.customer_mobile
     *
     * @return the value of user_order.customer_mobile
     *
     * @mbggenerated
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.customer_mobile
     *
     * @param customerMobile the value for user_order.customer_mobile
     *
     * @mbggenerated
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile == null ? null : customerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.customer_city
     *
     * @return the value of user_order.customer_city
     *
     * @mbggenerated
     */
    public Integer getCustomerCity() {
        return customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.customer_city
     *
     * @param customerCity the value for user_order.customer_city
     *
     * @mbggenerated
     */
    public void setCustomerCity(Integer customerCity) {
        this.customerCity = customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.customer_address
     *
     * @return the value of user_order.customer_address
     *
     * @mbggenerated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.customer_address
     *
     * @param customerAddress the value for user_order.customer_address
     *
     * @mbggenerated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_price
     *
     * @return the value of user_order.order_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_price
     *
     * @param orderPrice the value for user_order.order_price
     *
     * @mbggenerated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.pay_status
     *
     * @return the value of user_order.pay_status
     *
     * @mbggenerated
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.pay_status
     *
     * @param payStatus the value for user_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.create_time
     *
     * @return the value of user_order.create_time
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.create_time
     *
     * @param createTime the value for user_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.update_time
     *
     * @return the value of user_order.update_time
     *
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.update_time
     *
     * @param updateTime the value for user_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", shopId=").append(shopId);
        sb.append(", customerId=").append(customerId);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerMobile=").append(customerMobile);
        sb.append(", customerCity=").append(customerCity);
        sb.append(", customerAddress=").append(customerAddress);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}