package com.boilerplate.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

public class UserOrderItem implements Serializable {
    /**
     * 订单商品ID
     * 表字段 : user_order_item.item_id
     * @mbggenerated
     */
    private Long itemId;

    /**
     * 商品名称
     * 表字段 : user_order_item.item_name
     * @mbggenerated
     */
    private String itemName;

    /**
     * 商品价格
     * 表字段 : user_order_item.item_price
     * @mbggenerated
     */
    private BigDecimal itemPrice;

    /**
     * 订单号
     * 表字段 : user_order_item.order_id
     * @mbggenerated
     */
    private Long orderId;

    /**
     * 商家ID
     * 表字段 : user_order_item.shop_id
     * @mbggenerated
     */
    private Long shopId;

    /**
     * 用户ID
     * 表字段 : user_order_item.customer_id
     * @mbggenerated
     */
    private Long customerId;

    /**
     * 状态
     * 表字段 : user_order_item.status
     * @mbggenerated
     */
    private Short status;

    /**
     * 创建时间
     * 表字段 : user_order_item.create_time
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.item_id
     *
     * @return the value of user_order_item.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.item_id
     *
     * @param itemId the value for user_order_item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.item_name
     *
     * @return the value of user_order_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.item_name
     *
     * @param itemName the value for user_order_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.item_price
     *
     * @return the value of user_order_item.item_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.item_price
     *
     * @param itemPrice the value for user_order_item.item_price
     *
     * @mbggenerated
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.order_id
     *
     * @return the value of user_order_item.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.order_id
     *
     * @param orderId the value for user_order_item.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.shop_id
     *
     * @return the value of user_order_item.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.shop_id
     *
     * @param shopId the value for user_order_item.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.customer_id
     *
     * @return the value of user_order_item.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.customer_id
     *
     * @param customerId the value for user_order_item.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.status
     *
     * @return the value of user_order_item.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.status
     *
     * @param status the value for user_order_item.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_item.create_time
     *
     * @return the value of user_order_item.create_time
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_item.create_time
     *
     * @param createTime the value for user_order_item.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itemId=").append(itemId);
        sb.append(", itemName=").append(itemName);
        sb.append(", itemPrice=").append(itemPrice);
        sb.append(", orderId=").append(orderId);
        sb.append(", shopId=").append(shopId);
        sb.append(", customerId=").append(customerId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}