package com.boilerplate.server.mapper;

import com.boilerplate.server.model.UserOrderItem;
import com.boilerplate.server.model.UserOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int countByExample(UserOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int deleteByExample(UserOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int insert(UserOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int insertSelective(UserOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    List<UserOrderItem> selectByExample(UserOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserOrderItem record, @Param("example") UserOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserOrderItem record, @Param("example") UserOrderItemExample example);
}