package com.boilerplate.server.mapper;

import com.boilerplate.server.model.UserOrder;
import com.boilerplate.server.model.UserOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    List<UserOrder> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserOrder record, @Param("example") UserOrderExample example);
}