server:
  context-path: /
  port: 9010

logging:
  path: /tmp/logs

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    register-mode: instance
    address: nacos://localhost:8848?namespace=31eb021a-8887-4425-b403-6bcbf6b8fefc

mybatis-plus:
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:com/boilerplate/server/mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.boilerplate.server.model

management:
  health:
    db:
      enabled: false

spring:
  redis:
    redisson:
      file: classpath:redisson.yml
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）

  datasource:
    # 动态数据源配置
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/uyes_ptj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
          username: root
          password: root
      # 指定默认数据源名称
      primary: master

  shardingsphere:
    # 定义数据源
    datasource:
      names: ds0,ds1,ds2,ds3
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: root
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: root
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: root
    props:
      # 日志显示SQL
      sql.show: true
    sharding:
      tables:
        # 订单表
        user_order:
          # 真实表
          actualDataNodes: ds$->{0..3}.user_order_$->{0..15}
          # 分库策略
          databaseStrategy:
            complex:
              sharding-columns: order_id,customer_id
              algorithm-class-name: com.boilerplate.server.config.OrderShardingAlgorithm
          # 分表策略
          tableStrategy:
            complex:
              sharding-columns: order_id,customer_id
              algorithm-class-name: com.boilerplate.server.config.OrderShardingAlgorithm
        # 订单商品表
        user_order_item:
          # 真实表
          actualDataNodes: ds$->{0..3}.user_order_item_$->{0..15}
          # 分库策略
          databaseStrategy:
            complex:
              sharding-columns: order_id,customer_id
              algorithm-class-name: com.boilerplate.server.config.OrderShardingAlgorithm
          # 分表策略
          tableStrategy:
            complex:
              sharding-columns: order_id,customer_id
              algorithm-class-name: com.boilerplate.server.config.OrderShardingAlgorithm
      bindingTables:
        - user_order,user_order_item