spring:
  application:
    name: app.boilerplate.server
  profiles:
    active: @profileActive@

elasticsearch:
  host: 127.0.0.1
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500

