server:
  context-path: /
  port: 9010

logging:
  path: /tmp/logs

spring:
  datasource:
    url: jdbc:mysql://10.235.25.242:3306/tvgame?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 10.235.25.242 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）