server:
  context-path: /
  port: 9010

logging:
  path: /tmp/logs

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uyes_ptj?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6389 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）